### ISSUE TITLE
How are variants identified?

### ISSUE THREAD

**Issue by swvanderlaan** [bvilhjal/ldpred#10]
Hi,

When synchronising files (the reference with the summary statistics and the validation data), how are variants identified? Is that based on the dbSNP rs-id? Or is that based on chr:bp:alleleA_alleleB? Or something else?

In my case, this may have some practical implications when using LDpred, which I need then to address.

Thanks,

Sander

**Comment by tianbu** [comment]
I have the same problem too.

**Comment by choishingwan** [comment]
According to the code, it seems to be matching solely based on the rs-id

**Comment by bvilhjal** [comment]
Yes, I apologise the late reply on this, but @choishingwan is correct, that it's matching solely on rs-ids.
