### ISSUE TITLE
bugs report

### ISSUE THREAD

**Issue by mxcai** [bvilhjal/ldpred#100]
There are two bugs to be fixed.
1. sum_stats_parsers.py, line 266:
 N = float(header_dict[ncol]) should be changed as N = float(l[header_dict[ncol]])

2. validate.py, line 145:
Warning('More than 0.2f%% of variants...) should be changed to Warning('More than %0.2f%% of variants...)

**Comment by bvilhjal** [comment]
I apologize the slow reply.  Thanks for this bug report, these have now been fixed.
