### ISSUE TITLE
hapmap 3 reference information

### ISSUE THREAD

**Issue by agnetelundgaard** [bvilhjal/ldpred#102]
Hi Bjarni, 
It is possible to get some information on the HapMap 3 reference data used for the --only-hm3 flag? I'm not using rs as SNPs IDs, so I would appreciate information on the data source for the HapMap 3 reference to ensure that I can merge my data properly. 
Thank you :)
Best, 
Agnete

**Comment by bvilhjal** [comment]
Hi Agnete,

It’s described here:  https://www.broadinstitute.org/medical-and-population-genetics/hapmap-3 <https://www.broadinstitute.org/medical-and-population-genetics/hapmap-3> 

More specifically, I used the same file as LDscore (Bulik-Sullivan et al., Nat Genet 2015) uses, i.e. https://data.broadinstitute.org/alkesgroup/LDSCORE/hapmap3_snps.tgz <https://data.broadinstitute.org/alkesgroup/LDSCORE/hapmap3_snps.tgz> 

Best,
Bjarni

**Comment by agnetelundgaard** [comment]
Thank you, Bjarni - this is very helpful!
Best, 
Agnete
