### ISSUE TITLE
got an error message with finding chromosomes in ldpred

### ISSUE THREAD

**Issue by mindy1315** [bvilhjal/ldpred#104]
Hi, recently I'm working on ldpred but I got an error message with coordinating data.
The error message is like this..

" Note: For maximal accuracy all SNPs with LDpred weights should be included in the validation data set.
    If they are a subset of the validation data set, then we suggest recalculate LDpred for the overlapping SNPs.
    You can coordinate across the three data sets by either using the same LD reference and the validation data, or using
    the --vbim argument, and supply the validation data set PLINK formatted bim file.

Preparing to parse summary statistics
Parsing SNP list
Parsing bim file: /data1/ahminji/prs/ldpred/1kg.phase3.auto.snp.qc.eur.bim
11929993
Parsing the file: /data1/ahminji/prs/ldpred/ldpredsummarystat1
chr     pos     ref     alt     reffrq  rs      pval    effalt

SS file loaded, now sorting and storing in HDF5 file.
0 SNPs parsed from summary statistics file.
Unable to find phenotype values.
Genotype dictionary filled
Working on chromsome: chrom_1
"Unable to open object (object 'chrom_1' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_2
"Unable to open object (object 'chrom_2' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_3
"Unable to open object (object 'chrom_3' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_4
"Unable to open object (object 'chrom_4' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_5
"Unable to open object (object 'chrom_5' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_6
"Unable to open object (object 'chrom_6' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_7
"Unable to open object (object 'chrom_7' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_8
"Unable to open object (object 'chrom_8' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_9
"Unable to open object (object 'chrom_9' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_10
"Unable to open object (object 'chrom_10' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_11
"Unable to open object (object 'chrom_11' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_12
"Unable to open object (object 'chrom_12' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_13
"Unable to open object (object 'chrom_13' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_14
"Unable to open object (object 'chrom_14' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_15
"Unable to open object (object 'chrom_15' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_16
"Unable to open object (object 'chrom_16' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_17
"Unable to open object (object 'chrom_17' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_18
"Unable to open object (object 'chrom_18' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_19
"Unable to open object (object 'chrom_19' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_20
"Unable to open object (object 'chrom_20' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_21
"Unable to open object (object 'chrom_21' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
Working on chromsome: chrom_22
"Unable to open object (object 'chrom_22' doesn't exist)"
Did not find chromsome in SS dataset.
Continuing.
There were 0 SNPs in common
In all, 0 SNPs were excluded due to nucleotide issues.
Done coordinating genotypes and summary statistics datasets."

I guess this is system-related problem, but not sure about why this is happened.
Could you look over my error message and give any advice?

Thanks in advance.

**Comment by bvilhjal** [comment]
I apologize the slow reply on this. Try the latest version of LDpred, and then I think it should work.

**Comment by bvilhjal** [comment]
I think the issue that you’re observing is because it can’t match the SNPs across datasets properly.  LDpred matches the SNPs using the rsIDs, hence please ensure they match between datasets before using LDpred.
