### ISSUE TITLE
Can you add the BASIC format

### ISSUE THREAD

**Issue by gmgaous** [bvilhjal/ldpred#106]
When I ran the command python LDpred.py coord, I tried to use the --ssf-format BASIC. It seems the new version cannot accept BASIC format.  Can you modify you code to accept BASIC. Thank you.
The versions older than 1.0.0 (such as 0.9.9)can accept BASIC format.

**Comment by bvilhjal** [comment]
Hi, 

I apologize for the slow reply on this.  I believe I've now fixed this on the development branch.

Best,
Bjarni

**Comment by gmgaous** [comment]
Thanks a lo!
Guimin
