### ISSUE TITLE
My GWAS hits are too significant for LDpred

### ISSUE THREAD

**Issue by lassefolkersen** [bvilhjal/ldpred#108]
![Capture](https://user-images.githubusercontent.com/1732847/66201614-09813b00-e6a4-11e9-9621-23a2c6969645.PNG)

In a multi protein level GWAS I can use LDpred on 68 of the 92 proteins. But 14 protein fails, in spite of having the same format. Only difference is that these 14 have P-values that are less than 1e-300.  The error message is as above, outputting the acronym W.T.F which is exactly what I thought, _well that's funny_. It is funny. Gonna re-run with artificially modulated P-values, but maybe nice to know for you.

**Comment by bvilhjal** [comment]
Hi Lasse, I believe I've now fixed this issue!  

Thanks for using LDpred.

**Comment by lassefolkersen** [comment]
Thanks!
