### ISSUE TITLE
Raw beta and LDpred beta are reported for opposite alleles

### ISSUE THREAD

**Issue by rkwalters** [bvilhjal/ldpred#11]
Hi,

Thanks for all your work developing and maintaining ldpred! I've encountered some uncertainty in interpreting the txt files of LDpred betas that I think is a bug and I'm hoping you can clarify.

In the `*__LDpred_p{PS}.txt` and `*_LDpred-inf.txt` results files output by `ldpred.py`, the `raw_beta` and `ldpred_beta` appear to report effects for opposite alleles. Specifically, `raw_beta` reports the effect of allele `nt1` from the input summary statistics, and `ldpred_beta` reports an estimated effect for allele `nt2`.

Some motivating observations in this direction:
* Most of the time `raw_beta` and `ldpred_beta` have opposite signs
* That sign discordance between the betas occurs most reliably for the most significant SNPs in the input GWAS (i.e. the cases where LDpred estimation would be least expected to end up flipping the sign due to conditioning on surrounding SNPs).
* Comparison to the input GWAS shows the `raw_beta` consistently matching the input effect size for allele `nt1`, including correctly tracking cases where alleles had to be swapped to match the LD reference panel.
* PRS scoring with the `ldpred_beta` and allele `nt1` leads to scores negatively correlated with the expected phenotype (vs. trending in the expected direction when scoring `nt2`)

As far as I can tell, this is caused by how `coord_genotypes.py` sets up tracking both the raw GWAS effect size (stored in `chrom_dict[chrom]['log_odds']`, e.g. line 316) vs. the standardized effect size derived from the p-value (`chrom_dict[chrom]['betas']`, e.g. line 317-319). The key element is that the signed standardized effect is computed as:
```
beta = sp.sign(raw_beta) * stats.norm.ppf(pval / 2.0)
```
which appears to be intended to maintain the sign of the input effect while getting a Z score from the GWAS p-value. But `stats.norm.ppf(pval / 2.0)` will always be negative (given p/2 will always lead to a quantile in the lower tail of the normal distribution), so instead of matching `sign(raw_beta)` the standardized beta used for input to LDpred modeling will always be sign-flipped from the raw beta. This then carries through and shows up as being equivalent to having scores for `nt2` from LDpred in the output.

I guess my question then is:
1) Is this a correct understanding of current LDpred output?
2) Is this intentional? (I imagine not, but possible I've missed some other motivation)
3) If it's a bug, is there a good route to fixing it? Correcting the `stats.norm.ppf()` calculation seems simple enough, but I'd worry about breaking people's existing workflows (thus why I'm not just submitting a pull request). Perhaps better to flip `raw_beta` to also be the effect of allele `nt2`? Or at worst just provide some clear documentation of how the two betas are oriented?
[edit to add:] 4) I haven't checked how the sign flip impacts the `validate.py` script downstream. Probably worth looking at, and may inform the best course of action for fixes, if any?

Cheers,
Raymond

(cc @ce-carey who helped identify this)

**Comment by jprnz** [comment]
Assuming this was unintentional, @liangyy has caught this in their fork and has addressed it [here](https://github.com/liangyy/ldpred/commit/9e401a4c1123b4f0c4a037c6ffcdd6c28839ed10). This seems like a sensible solution.

In fact, @liangyy has identified at least one other potential bug and added quite a few niceties which @bvilhjal might want to consider merging.

**Comment by bvilhjal** [comment]
I apologise for my very slow response, but I left science (for now) and haven’t really maintained LDpred (nor responded to LDpred emails) for the last couple of years. 

Thanks for reporting this issue!

The reason for the sign difference is that some people use logistic reg effect estimates and others linear reg effect estimates in their summary stats.  Depending on what you use, you end up with opposite signed risk scores.
 
Regarding stats.norm.ppf, as (pval/2.0)<=0.5 then stats.norm.ppf(pval/2.0)<=0.  Hence taking the absolute will only change the sign of the effect.  However, if that is what you want, then that’s good 😊

I'll close this issue for now, but if you have good ideas for how to improve the code, please do so, and consider submitting a pull request with the changes to update the repository.

Best,
Bjarni
