### ISSUE TITLE
Questions about the logs: 'Current PRS correlation', 'The slope for predictions with weighted effects' etc.

### ISSUE THREAD

**Issue by YiweiNiu** [bvilhjal/ldpred#113]
Hi,

Thank you for this cool tool!

I am starting using LDPred few days ago and have some basic questions about the logs. Specifically, I do not know the meaning of the following terms:

```shell
Current PRS correlation: -0.2097
Current PRS r2: 0.0440
PRS correlation: -0.2097
Variance explained (Pearson R2) by PRS: 0.0440
The slope for predictions with weighted effects is: -0.6751
```

Could you please give me some guides about understanding these? Sorry if the question is too obvious.

Bests,
Yiwei

**Comment by bvilhjal** [comment]
These are internal values, which you can probably ignore.  
"Current PRS correlation/r2" denotes the PRS correlation/r2 using the SNPs included so far.
"PRS correlation: -0.2097" is the final correlation
"Variance explained (Pearson R2) by PRS: 0.0440" and the final R2
"The slope for predictions with weighted effects is: -0.6751"  is the calibration of the PRS.

I hope this helps.

Best,
Bjarni
