### ISSUE TITLE
BUG in LDpred-inf model

### ISSUE THREAD

**Issue by wavefancy** [bvilhjal/ldpred#12]
Dear developers,

I think there's a bug for the LDpred-inf model, the local variable 'n_snps' [LDpred.py: Line 223 and Line 225] didn't get reset for each chromosome in this model, however, the value of this variable borrowed the value from line 196, therefore, it always keeps the value for chr22, no matter which chr it runs in. In this case, the LD_score estimates on the other chrs are biased.

Best regards
Wallace

**Comment by bvilhjal** [comment]
Great catch!  Thanks!
