### ISSUE TITLE
Best correlation score 

### ISSUE THREAD

**Issue by jPontix** [bvilhjal/ldpred#124]
I calculated the polygenic scores but, how to know which file has the best correlation score?

**Comment by bvilhjal** [comment]
Thanks for your question.  It should be reported in the terminal output.

**Comment by jPontix** [comment]
So if I would like to see again I should have to run again the script... Ok, thanks

**Comment by bvilhjal** [comment]
You can also just load the polygenic score and the phenotype file into R or ipythont/pandas, and use that to examine what score is most accurate.

Would it have been better if LDpred stored all in a log?

**Comment by Abdelmonsif** [comment]
Yes, it would be better
