### ISSUE TITLE
Can LDpred run for each chromosome now?

### ISSUE THREAD

**Issue by ChongWu-Biostat** [bvilhjal/ldpred#129]
Dear Author,

I just have one question. Can LDpred run for each chromosome now? What's your suggestions? Do we need to combine the reference sample for each chromosome before running LDpred? Thank you for your suggestions and time in advance.

Thanks,
Chong

**Comment by bvilhjal** [comment]
Hi,

LDpred does in fact derive the polygenic scores for each chromosome independently (by default), but it does not currently do that in parallel, i.e. it runs these in sequence.  However, I would like to parallelize this in the future, e.g. using dask, but I havn't gotten round to do that.

Best,
Bjarni

**Comment by ChongWu-Biostat** [comment]
Got it. Thank you for clarification.

Thanks,
Chong

---
Chong Wu
Assistant Professor
Department of Statistics 
The Florida State University

**Comment by pablogargon** [comment]
Hi @bvilhjal ,
This means it is not possible to add the scores calculated at each chromosome separately to obtain the individual's full PRS? Would this violate any assumptions of LDpred's statistical model?
Thanks,
P
