### ISSUE TITLE
bug report on printing 'chrom'

### ISSUE THREAD

**Issue by bastia1989** [bvilhjal/ldpred#14]
https://github.com/bvilhjal/ldpred/blob/dbe971d8b8dc0cb676b286a45499c7ff3a3fa9b6/ldpred/coord_genotypes.py#L1003

Here the variable `chrom` is of type **string** rather than **integer**.

**Comment by bvilhjal** [comment]
Thanks for noting this.  I'm finally finding time to fix these things.

**Comment by rbpeng** [comment]
Hey @bvilhjal, thank you for your work in maintaining LDpred!

I think I found another issue similar to this one. In line 992, I think the `%d` in `g = ssg.create_group('chrom_%d' % chrom)` should be replaced with `%s`. Line 670 has the same issue. I was having issues with getting the BASIC format to work, but I got `coord_genotypes.py` to work after I fixed this.

**Comment by bvilhjal** [comment]
I fixed this as well now, thanks.

**Comment by marielohcs** [comment]
FYI - Don't think it is fixed for Line 670 :) Only line 992
