### ISSUE TITLE
Running LDpred without running setup.py

### ISSUE THREAD

**Issue by choishingwan** [bvilhjal/ldpred#148]
Hi @bvilhjal , 

Is it possible to run the latest version of LDPred without running setup.py? We noticed that the LDPred.py file no longer exists in the directory, which was previously used as the entry point of LDPred. 

The main reason I asked is that it seems to make it much more difficult for us to inspect the code to find out reason of failure of LDPred.

**Comment by bvilhjal** [comment]
Hi @choishingwan,

I apologize for lack of replies. Please try LDpred2, it’s much faster and better.

https://privefl.github.io/bigsnpr/articles/LDpred2.html

**Comment by choishingwan** [comment]
Does that mean LDPred 1.011 is now discontinued? Was trying to update our LDPred tutorial to v1.011 but encountered some cryptic error messages.

**Comment by bvilhjal** [comment]
It likely will, but hopefully I'll find time to update it before.  I plan to make the announcement of switching to LDpred2 when we update the bioRxiv paper, in a few weeks.

Would it be possible to switch to LDpred2 in your work?  It's now in R, which could be a problem.

**Comment by choishingwan** [comment]
I see. I can surely switch it to LDpred2. Was only trying to include it in our tutorial (see [here](https://choishingwan.github.io/PRS-Tutorial/ldpred/)), nothing special
