### ISSUE TITLE
coord_genotypes.py consistently unable to find final chromosome in SSF?

### ISSUE THREAD

**Issue by rbpeng** [bvilhjal/ldpred#17]
Hey Bjarni,

Thank you for all the work you've done on LDpred! 

I'm currently running into a recurring issue with `coord_genotypes.py` in that when coordinating the validation data, LD reference data, and SSF, `coord_genotypes` is unable to find the last chromosome in the SSF. I have tried both using a BASIC and STANDARD format SSF, and I encountered the issue with both. For instance, if I have a SSF with GWAS summary statistics for chromosomes 1-22, as well as chromosome X, then I run into 
`Working on chromsome: chrom_X`
`"Unable to open object (object 'chrom_X' doesn't exist)"`
`Did not find chromsome in SS dataset.`
`Continuing.`
in the last step of the coordination, even though `coord_genotypes` was able to work on every other chromosome. 

However, if I have a SSF with GWAS summary statistics for only one chromosome (say, chromosome X), then I don't run into this issue and `coord_genotypes` is able to find the chromosome in the SSF and do the coordination. Do you know what the issue could be? Thank you!

**Comment by bvilhjal** [comment]
Hi, 

Thanks for this.  Do you have a summary statistics file that I can use to debug?  I'm just interested in knowing whether it has summary statistics for chromosome X or 23, and how it is formatted.

Best,
Bjarni

**Comment by rbpeng** [comment]
Thanks for looking into the issue. Here is a
[small SSF in BASIC format](https://github.com/bvilhjal/ldpred/files/2592604/pgc_schizophrenia_ssf_BASIC_for_troubleshooting.txt) that I created from the full SSF by taking a random sample of 20 SNPs from each chromosome.

I then ran `coord_genotypes.py` with this small SSF and my genotype files, and here is a 
[log of the output](https://github.com/bvilhjal/ldpred/files/2592607/test_output.log), which will hopefully be helpful for debugging. Even though the SSF has summary statistics for both chromosome 23 and X, you can see that I got the following error:
`Working on chromsome: chrom_23`
`"Unable to open object (object 'chrom_23' doesn't exist)"`
`Did not find chromsome in SS dataset.`

So it seems like it's unable to find `chrom_23` even when both both chromosome 23 and X are in the SSF. Any help with this issue would be greatly appreciated.

**Comment by bvilhjal** [comment]
Hi, 

I believe I've figured out the issue.  It turns out that it only looked for chromosomes 1-22, and required chromosome to be noted using a capital "X".  I apologize for not catching this earlier.  

I've fixed the code, but I committed it on the develop branch.  You can obtain it by switching to that git branch, and pull.  I plan to merge this branch to the main by the end of the month.  I have a couple of more bugfixes and improvements that I'd like to add first.

Best,
Bjarni
