### ISSUE TITLE
Errors with validate.py 

### ISSUE THREAD

**Issue by bioinf173** [bvilhjal/ldpred#18]
Hello, 

I have completed the first two stages of LDRED -  coord_genotypes.py & LDpred.py. These have generated a number of files 
_coord.hdf5
ldpred_LDpred-inf.txt
....
LDpred_p1.0000e+00.txt
None_ldradius437.pickled.gz_

My Phenotype.txt file is a FAM format.  Currently, I have 59529 free memory (ram) on my computer.

Now I would like to proceed to the file stage - validate.py - that will actually create the polygenic scores and give some summary statistics. For this I used the following command lines: 
 
`python validate.py --vgf=My_Data --rf=LDpred-inf.txt --pf=Phenotype.txt --rf=STANDARD --out=my_results_valid`

However, this message comes up and nothing else happens: 
```
Phenotype.txt
Parsing phenotypes
```

When I remove the phenotype from the command line, I get the following error:
```
Parsing phenotypes
Traceback (most recent call last):
  File "ldpred/validate.py", line 754, in <module>
    main()
  File "ldpred/validate.py", line 689, in main
    assert num_individs > 0, 'No phenotypes were found!'
AssertionError: No phenotypes were found!
```
I am not sure why I get this error as providing a phenotype is optional at this stage.

I will be grateful for any advice on how to deal with these error and successfully build polygenic scores. 

Thank you very much in advance.

**Comment by bvilhjal** [comment]
Thanks for using LDpred.  It seems to me that you made a small error in the flags.  You specify --rf twice, and you should also set --pf_format=FAM

I hope that helps.

Best,
Bjarni

**Comment by bioinf173** [comment]
Thank you for your response. I have corrected the mistake and also included `--pf_format=FAM`. However, the same message appears on the screen and nothing else happens: 

```
Phenotype.txt
Parsing phenotypes
```
 I will be grateful for your advice on how I can overcome this issue and build polygenic scores.

Many thanks

**Comment by bvilhjal** [comment]
Is Sex defined?  In order for me to better debug this, do you have an example of the phenotype file, e.g. the first couple of lines?

**Comment by bioinf173** [comment]
Dear Bjarni,

Of course. Here are a couple lines from the phenotype file: 
head Phenotype.txt
EG140001 EG140001 0 0 2 10
EG140002 EG140002 0 0 2 10
EG140003 EG140003 0 0 2 10
EG140004 EG140004 0 0 2 15

Sex is coded as'1' = male, '2' = female, '0' = unknown.  No header.

Thank you very much for your help with this. 
With kind wishes.

**Comment by bioinf173** [comment]
Hi,
Thank you very much for this. I have just re-run the analysis using the modified code. 

```
python ldpred-master/ldpred/validate.py --vgf=My_Data \ 
--rf=LDpred_p1.0000e+00.txt \
--pf=Phenotype.txt --pf_format=FAM \
--TS=1,0.3,0.1,0.03,0.01,0.003,0.001,0.0003,0.0001,3E-5,1E-5,1E-6,1E-7,1E-8 \
--PS=1,0.3,0.1,0.03,0.01,0.003,0.001,0.0003,0.0001 \
--out=Results/
```
I get the following message on the screen but no results appears on the screen on the results folder 
```
Phenotype8.txt
Parsing phenotypes
Parsed 6926 phenotypes successfully
```
I will be grateful for your advice on how I can overcome this and build the scores. 

Thank you very much.

**Comment by bvilhjal** [comment]
I believe the issue is that you set --rf to a specific file, and not the prefix.

Try --rf=LDpred instead of --rf=LDpred_p1.0000e+00.txt

Hope this works.

**Comment by bioinf173** [comment]
Thank you. I have just tried `--rf=LDpred` instead of `--rf=LDpred_p1.0000e+00.txt`, but the same outcome occurred. A message was printed on the screen and nothing else happened. 

```
Phenotype.txt
Parsing phenotypes
Parsed 6926 phenotypes successfully
```

I will be grateful for your advice on how I can overcome this and build the scores.
Thank you very much.

**Comment by bvilhjal** [comment]
I apologize, I made a mistake,  --rf=  should point to whatever you used for --out in the previous step.  Writing LDpred was wrong.  I also update the code now to provide a small improvement in error messaging when this happens.

**Comment by bioinf173** [comment]
It is perfect!  It is working like magic at the moment. Thank you so much for your patience and help with this!
