### ISSUE TITLE
coord_genotypes.py mysteriously stops w/o reporting error while working on e.g. chr7 or 10

### ISSUE THREAD

**Issue by marielohcs** [bvilhjal/ldpred#29]
Hi, it appears that when I run coord_genotypes.py, after parsing all the SNPs across all 22 chromosomes from the summary statistics file, the code mysteriously stops while working on chromosome 7... No error messages, it just stops (log file attached)....

I am also running another model with the same genotype files on another set of summary statistics, and in this case, it stops at chromosome 10....

So I guess we know the problem is not with the genotype files, since the same genotype files were used in the 2 models....

Please help! Thanks!! 
[log_SASscore.txt](https://github.com/bvilhjal/ldpred/files/2717271/log_SASscore.txt)

**Comment by bvilhjal** [comment]
Hi, 

This looks a bit mysterious. Did you try running using fewer SNPs, just to see if it ran through?  Also, could it be something like a wall-time limit?

**Comment by bvilhjal** [comment]
Hi, I made a lot of changes.  So if you're up for trying it again, then try checking the code out from github.

Cheers,
Bjarni

**Comment by marielohcs** [comment]
Thanks!
Sorry i got sucked into grant rebuttal etc - will definitely try again!
Cheers,
Marie

Sent from my Huawei phone


-------- Original Message --------
Subject: Re: [bvilhjal/ldpred] coord_genotypes.py mysteriously stops w/o reporting error while working on e.g. chr7 or 10 (#29)
From: "Bjarni J. Vilhjalmsson"
To: bvilhjal/ldpred
CC: "Loh, Marie" ,Author


Hi, I made a lot of changes. So if you're up for trying it again, then try checking the code out from github.

Cheers,
Bjarni
