### ISSUE TITLE
AssertionError infinite betas. 

### ISSUE THREAD

**Issue by cburik** [bvilhjal/ldpred#3]
Hi, 

I'm getting an assertion error message:

    Working on chromsome: chrom_3
    Traceback (most recent call last):
      File "/home/cburik/Tools/ldpred-master/ldpred/coord_genotypes.py", line 1836, in <module>
        main()
      File "/home/cburik/Tools/ldpred-master/ldpred/coord_genotypes.py", line 1824, in main
        hdf5_file=h5f, min_maf=p_dict['maf'], skip_coordination=p_dict['skip_coordination'])
      File "/home/cburik/Tools/ldpred-master/ldpred/coord_genotypes.py", line 1212, in coordinate_genot_ss
        assert not sp.any(sp.isinf(betas)), 'WTF?'
    AssertionError: WTF?

This seems to happen when including SNPs with an extremly low p-value (this is one of them: 1.7E-431). These p-values are rounded to 0 when converting them into floats. 

Haven't gone over your code extensively, but maybe one option is using numpy.longdouble for increased precision. 

LDpred does run when I exclude the SNPs in question. 

best,

Casper

**Comment by sarahgra** [comment]
I'm also getting the same assertion error.  Just wondering if you were ever able to get ldpred to work with the small p-values?

**Comment by cburik** [comment]
No I haven't.

**Comment by daniel-hui** [comment]
Hi, we also had the same problem. We were able to run LDpred with the small p-values by setting them to just under the min value allowed (eg. 2.225e-308, where the min Python 2.7 float value is 2.2250738585072014e-308), however we have not been able to use the original values.

**Comment by bvilhjal** [comment]
Dear Daniel-Hui, thanks for reporting this.   I apologize for this limitation, I am currently looking into updating LDpred, and will consider this issue.
