### ISSUE TITLE
ldpred installs successfully, but an error shows up on import 

### ISSUE THREAD

**Issue by annashcherbina** [bvilhjal/ldpred#30]
successful installation with pip: 

 pip show ldpred 
Name: LDpred
Version: 0.9.9
Summary: A Python package that adjusts GWAS summary statistics for the effects of linkage disequilibrium (LD)
Home-page: https://github.com/ldpred
Author: Bjarni J Vilhjalmsson
Author-email: bjarni.vilhjalmsson@gmail.com
License: MIT
Location: /scratch/users/annashch/miniconda3/lib/python3.6/site-packages/LDpred-0.9.9-py3.6.egg
Requires: h5py, scipy, plinkio
Required-by: 

In python: 

`import ldpred `

yields: 

miniconda3/lib/python3.6/site-packages/LDpred-0.9.9-py3.6.egg/ldpred/__init__.py", line 11, in <module>
ModuleNotFoundError: No module named 'LDpred'

This is installing with pip on python 3.6. The same behavior is observed when installing from source in python 3.6 from the master branch.

**Comment by privefl** [comment]
I get the same error when running `coord` using Python 3.7 installed via anaconda3.

**Comment by jackosullivanoxford** [comment]
I get the same error...

**Comment by bvilhjal** [comment]
Hi,

LDpred shouldn't work with python3 yet, and I'm surprised that pip actually has it for python 3.6?  I'm actually planning to make sure it works for python 3 this week.

**Comment by jackosullivanoxford** [comment]
Have you fixed this yet? I still get the same error
In python: 
`import ldpred`

yields: 
No module named 'LDpred'

**Comment by bvilhjal** [comment]
Hi, I just made the switch to python3, so if you check it out from github, it should (hopefully) work.
