### ISSUE TITLE
LDpred.py and validate.py produce different R^2

### ISSUE THREAD

**Issue by borisevichdi** [bvilhjal/ldpred#31]
Summary: LDpred.py and validate.py treat missing values in plink data differently. LDpred does not filter missing values (represented as -9), uses them for correlation coefficient calculation, and thus calculates incorrect R^2. validate.py filters the missing values properly, and calculates proper R^2 and other metrics.

0. Both coord_phenotypes.py and validate.py load phenotype data from plink .fam files.

1. coord_phenotypes.py relies on plinkfile.PlinkFile implementation:
https://github.com/bvilhjal/ldpred/blob/8a2f5153b20c1da6801bf7e86d44ffddd3b0c3be/ldpred/coord_genotypes.py#L1075-L1086
and
https://github.com/bvilhjal/ldpred/blob/8a2f5153b20c1da6801bf7e86d44ffddd3b0c3be/ldpred/coord_genotypes.py#L1342-L1365
This step does not have any filtering of the missing phenotypes (i.e. "-9").

2. coord_phenotypes.py produces hdf5, containing 'y' dataset, which is used downstream by LDpred.py, during R^2 calculation:
https://github.com/bvilhjal/ldpred/blob/8a2f5153b20c1da6801bf7e86d44ffddd3b0c3be/ldpred/LDpred.py#L255-L264

3. validate.py does not use hdf5 file and instead loads data directly using custom code: https://github.com/bvilhjal/ldpred/blob/8a2f5153b20c1da6801bf7e86d44ffddd3b0c3be/ldpred/validate.py#L284-L292
Here, filtering is properly implemented.

4. This difference in treating missing values will cause the R^2 calculated during LDpred.py runtime to be completely off, even if just one value per 1000 were messed up.

Bonus points: additional problem occurs if the .fam file has continuous phenotype, that has a value of 0. validate.py parses it correctly as 0. Interestingly, plinkfile.PlinkFile considers 0 as unknown value, and replaces it also with -9, i.e. missing value. I'm not quite sure, which should be considered the correct behavior. As a result, if .fam has 0 in continuous phenotype column, it will produce -9 in .hdf5 -> -9 will be used in LDpred R^2 estimate, whereas 0 will be used by validate.py.

**Comment by bvilhjal** [comment]
Hi, 

Thanks for pointing this out.  I never intended for LDpred to output final R2 values, but I will try to fix this.  I'm hoping to push out a version 1.0 very soon (weeks), where fixing this would make lots of sense.

**Comment by bvilhjal** [comment]
Hi, 

I've changed the code significantly to guide the user towards using the `LDpred.py score` for calculating scores and prediction R2.  Basically, they should only be using the R2 calculation in step 4 (unless in debug mode).  Providing R2 values earlier was just confusing.  I believe the program is now easier to use.

Hence, I'll close this issue.  Thanks for highlighting this!

Best,
Bjarni

**Comment by borisevichdi** [comment]
It definitely is easier, thank you a lot!

Best, Dmitrii
