### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by kateishim** [bvilhjal/ldpred#33]
Hi, 

Thanks for your great efforts in developing and maintaining LDpred.
I get the error message below repeatedly when I try to run `ldpred`. 

`ldpred --coord=/data1/ishim/GRS/coord --ld_radius=1000000 --local_ld_file_prefix=/data1/ishim/GRS/ld --PS=1,0.3,0.1,0.03,0.01,0.003,0.001,0.0003,0.0001 --N=184305 --out=/data1/ishim/GRS/out`

Could you let me know what I can do for this memory error?
How much memory would be needed? 

Traceback (most recent call last):
  File "/home/ishim1/.local/bin/ldpred", line 11, in <module>
    sys.exit(main())
  File "/home/ishim1/.local/lib/python2.7/site-packages/ldpred/LDpred.py", line 546, in main
    ret_dict = ld.get_LDpred_ld_tables(snps, ld_radius=p_dict['ld_radius'], ld_window_size=2*p_dict['ld_radius'])
  File "/home/ishim1/.local/lib/python2.7/site-packages/ldpred/ld.py", line 97, in get_LDpred_ld_tables
    D = sp.dot(X, X.T) / n
MemoryError

Thanks, 
Kate

**Comment by kaibios0101** [comment]
Hi, kateishim. Recently I also got this problem. From these code, I guess you use the CARDIoGRAMplusC4D summary statistics to construct a bayesian polygenic risk scores.  The ld_radius maybe not suitable and you may try a small radius, such as 2000 or 3000.

**Comment by bvilhjal** [comment]
Hi,

I agree with @kaibios0101 , try shrinking the radius, it's way too big.  Also, how large is your LD reference (in number of individuals).

**Comment by kateishim** [comment]
Thank you for your advice, @kaibios0101 and @bvilhjal!

I used 1000 Genomes European data (n=503) for LD reference. 
Do you think that setting LD radius to 2000 would be large enough to calculate LD-adjusted betas?

According to this page's explanation about LD radius below, would the LD radius be ~4000 (=11929993/3000) if my LD reference bim file has 11929993 markers?

LD_RADIUS: An integer number which denotes the number of SNPs on each side of the focal SNP for which LD should be adjusted. A value corresponding M/3000, where M is the number of SNPs used for the analysis is reasonable for genome length of 3000Mb. This should result in a LD-radius of about 1Mb on average.

Thank you very much for your help!

**Comment by kaibios0101** [comment]
Hi, kateishim. According to the README.md, it's better for you to use the common snps between validation dataset (11929993 as you provided) and summary statistics dataset as the M. And then you can compute the proper radius.

**Comment by kateishim** [comment]
According to your advice, I've got a number for LD radius from my data as 2411. Thanks a lot @kaibios0101 !!

**Comment by bvilhjal** [comment]
Hi Kate, sorry about the slow reply.  That sounds like a very very large radius.
