### ISSUE TITLE
Duplicate error with coord_genotypes.py

### ISSUE THREAD

**Issue by seunghun23** [bvilhjal/ldpred#34]
Hi,

Thank you for developing a great tool for PRS calculation. 
I ran the coord_genotypes.py script with a bed file of 1000 genome data as a LD reference genotype file and encountered following errors 
`Working on chromsome: chrom_2
Traceback (most recent call last):
  File "coord_genotypes.py", line 1836, in <module>
    main()
  File "coord_genotypes.py", line 1824, in main
    hdf5_file=h5f, min_maf=p_dict['maf'], skip_coordination=p_dict['skip_coordination'])
  File "coord_genotypes.py", line 1183, in coordinate_genot_ss
    assert len(g_sid_set) == len(g_sids), 'Some duplicates?'
AssertionError: Some duplicates?` 

Could you help me on this error?

Thanks,
SH

**Comment by seunghun23** [comment]
Hi again,

I figured out that the error above was due to duplicate SNPs in the 1000 genome vcf, so I made a new plink files without duplicate SNPs and that fixed the problem. However, I'm not getting an IndexError. Could you tell me how to fix this? 

![image](https://user-images.githubusercontent.com/38226390/51223731-117c2d80-1911-11e9-8ad4-b1cbfabbc7f0.png)

**Comment by bvilhjal** [comment]
Hi, I am sorry for the slow reply on this.  It seems like you have too few SNPs for LDpred to make sense. I do however also agree that the error messaging could be a lot better.

**Comment by seunghun23** [comment]
Hi bvilhjal,
thank you for the reply. Is there a minimum number of SNPs for LDpred to run? 
I am using GWAS summary statistics from GWAS Catalogue, and for many phenotypes I'm 
looking at, number of SNPs are less than 100 

-SH

**Comment by bvilhjal** [comment]
I recommend something between 100K and 2M SNPs.  You can find links to summary statistics on LD Hub (http://ldsc.broadinstitute.org/ldhub/) and other places.

**Comment by seunghun23** [comment]
Thanks a lot for introducing a great resource!
