### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by trptyrphe11** [bvilhjal/ldpred#35]
Hi, I am using python2.7 version, after pip install, calling the binary ldpred throws the following error:

ImportError: Python-Eggs/plinkio-0.9.6-py2.7-linux-x86_64.egg-tmp/plinkio/cplinkio.so: undefined symbol: PyUnicodeUCS2_FromString

**Comment by bvilhjal** [comment]
Hmm, not sure what this is, but perhaps you can try cloning it from github.
