### ISSUE TITLE
Coordination Matches a Small Proportion of SNPs

### ISSUE THREAD

**Issue by anderseng** [bvilhjal/ldpred#36]
When I run coord_genotypes.py to coordinate my PLINK LD reference panel and STANDARD formatted summary statistics, the stdout says "Found 658,473 SNPs present in both datasets".  I have compared the rsIDs in the LD reference panel .bim file and the STANDARD-formatted reference file and the position, alleles, and rsIDs match perfectly for 8,777,172 SNPs and if I only match on the rsIDs, then 8,801,185 SNPs should match between the two datasets.  I am really struggling to understand why only ~600,000 SNPs are present in both datasets when there should be 8M+ matching in both datasets.  Any thoughts on why this might be?

STDOUT:
```
8792766 SNPs parsed from summary statistics file.
Loaded 14518 controls and 1381 cases
Genotype dictionary filled
Working on chromsome: chrom_1
Found 658473 SNPs present in both datasets
89190 SNPs were excluded due to ambiguous nucleotides.
57785 SNPs were excluded due to non-matching nucleotides.
Iterating over file to load SNPs
raw_snps.shape= (511498, 15899)
511498 SNPs were retained on chromosome 1.
Normalizing SNPs
PRS correlation for chromosome 1 was 0.3448
Raw effect sizes PRS correlation for chromosome 1 was -0.3547
Now storing coordinated data to HDF5 file.
```

First few lines of STANDARD Summary Statisic File:
```
$ head STANDARD_LDpred_Input_SumStats_CVset1.txt
chr	pos	ref	alt	reffrq	info	rs	pval	effalt
chr1	768253	C	A	0.7174	1	RS2977608	0.7925	-0.0110388471152165
chr1	777232	C	T	0.9844	1	RS112618790	0.9219	0.00823380492710344
chr1	791853	G	A	0.98082	1	RS6684487	0.8196	0.017756721589259
chr1	908823	G	A	0.93251	1	RS28687780	0.8703	0.00783057911518861
chr1	909221	T	C	0.9775	1	RS62639985	0.6793	0.0375980304153184
chr1	909419	C	T	0.9202	1	RS28548431	0.1275	-0.0723206615796261
chr1	912049	C	T	0.6733	1	RS9803103	0.1886	-0.0452601314048646
chr1	913889	A	G	0.6026	1	RS2340596	0.2911	-0.0340148785872776
chr1	914333	G	C	0.6503	1	RS13302979	0.4158	-0.0268366539535596
```

First few lines of LD reference .bim file:
```
$ head GWAS1.allchr.bim
1	RS2977608	0	768253	A	C
1	RS112618790	0	777232	T	C
1	RS149821290	0	781367	C	A
1	RS6684487	0	791853	A	G
1	RS189398772	0	796799	C	A
1	RS114397781	0	870873	A	G
1	RS137904446	0	892237	A	C
1	RS28415373	0	893981	T	C
1	RS28687780	0	908823	A	G
1	RS62639985	0	909221	C	T
```

**Comment by anderseng** [comment]
Nevermind.  I realized that the 600,000 SNPs was referring only to Chromosome 1.  The run terminated early because I didn't request enough memory (100 GB is not enough...).

**Comment by bvilhjal** [comment]
I recommend filtering to hapmap3 SNPs, i.e. the same set of SNPs that LDscore regression uses.  Generally, I do not recommend running LDpred for more than 2M SNPs, both for memory reasons, but also because prediction accuracy is also typically reduced (e.g. because of imputation and LD estimation errors).
