### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by wym0072003** [bvilhjal/ldpred#40]
Hi Bjarni,

I have got coord result without errors, but I got issues in ldpred step:
Applying LDpred with LD radius: 15
Traceback (most recent call last):
  File "/usr/local/bin/ldpred", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ldpred/LDpred.py", line 571, in main
    ld_dict = ld_dict, n=p_dict['N'], num_iter=p_dict['num_iter'], h2=p_dict['H2'], verbose=False)
  File "/usr/local/lib/python2.7/dist-packages/ldpred/LDpred.py", line 201, in ldpred_genomewide
    chi_square_lambda = sp.mean(n * sum_beta2s / float(num_snps))

Would you please have a look what might cause this problem? Samples size is 6K and number of variant is 33K. Thanks!

best

Yiming

**Comment by bvilhjal** [comment]
Hi Yiming, 

I believe this error has been fixed in the current version here on github, just updated a couple of days ago.  Try checking it out.  I will soon add it on pip (I want to test it more first).  

Also, given your small number of SNPs, I'm not sure LDpred is very good.

Best,
Bjarni

**Comment by wym0072003** [comment]
Thank you very much! I will try it with more variant again.

best,

Yiming
