### ISSUE TITLE
coord -- KeyError in sum_stats_parsers.py

### ISSUE THREAD

**Issue by alussier17** [bvilhjal/ldpred#47]
Hello, I am getting an issue when running the following coord function: 

`python /home/alussier/ldpred/LDpred coord --gf home/alussier/1KGP_data/1kgp_euro_plink --ssf sum_stats.txt --N 159208 --out coord.hdf5 --chr chr --A1 Allele1 --A2 Allele2 --pos pos --rs MarkerName --pval P.value --eff Effect --beta --ssf-format CUSTOM`

sum_stats.txt file
```
MarkerName	Allele1	Allele2	chr	pos	Effect	StdErr	P.value
rs58108140	a	g	1	10583	0.064	0.0585	0.274
rs180734498	t	c	1	13302	0.1306	0.0681	0.05506
rs144762171	c	g	1	13327	0.4488	0.1873	0.01655
```

bim file first lines
```
1	rs548419688	0	10505	T	A
1	rs568405545	0	10506	G	C
1	rs534229142	0	10511	A	G
```

Output from LDpred
```
Preparing to parse summary statistics
Parsing summary statistics file: sum_stats.txt
Traceback (most recent call last):
  File "../ldpred/LDpred.py", line 245, in <module>
    main()
  File "../ldpred/LDpred.py", line 230, in main
    coord_genotypes.main(p_dict)
  File "/home/alussier/ldpred/ldpred/coord_genotypes.py", line 717, in main
    sum_stats_parsers.parse_sum_stats(h5f, p_dict, bimfile)
  File "/home/alussier/ldpred/ldpred/sum_stats_parsers.py", line 42, in parse_sum_stats
    pos=p_dict['pos'], input_is_beta=p_dict['beta'], debug=p_dict['debug'])
  File "/home/alussier/ldpred/ldpred/sum_stats_parsers.py", line 125, in parse_sum_stats_custom
    if not chrom == snps_pos_map[sid]['chrom']:
KeyError: 'rs58108140'
```

It seems to give an error if a SNP from the summary statistics file is not in the LD reference file - do these need to be filtered down beforehand? I am using python 3.6 and the most recent version of ldpred from github. 

Thanks,
Alex

**Comment by bvilhjal** [comment]
Thanks for reporting this.  I believe I've fixed this now.
