### ISSUE TITLE
Format of score file

### ISSUE THREAD

**Issue by privefl** [bvilhjal/ldpred#48]
This is the first 5 lines of the file I get using `python LDpred.py score`:
```
IID, true_phens, raw_effects_prs, pval_derived_effects_prs, sex
14, 1.000000e+00, -6.274195e+02, 1.954391e+00, 1, 
47, 0.000000e+00, -4.218925e+02, 1.958752e+00, 2, 
89, 0.000000e+00, -7.006771e+02, 2.584703e+00, 1, 
105, 0.000000e+00, -1.799069e+03, 6.776581e+00, 1, 
```
Would it be possible to have just a comma (or tabulation) separator (without an extra space) and no separator at the end?
It would be much easier to parse.

Thanks for your work updating LDpred.

**Comment by bvilhjal** [comment]
I believe I fixed this now.
