### ISSUE TITLE
coord TypeError in coord_genotypes.py

### ISSUE THREAD

**Issue by Ambrosinae** [bvilhjal/ldpred#49]
Hi, I'm currently running this command:

`python3 ldpred/LDpred.py coord --gf=chr1_plink.AllDuplicatesRemoved --ssf=GWAS_COMBO_hg38_chr1_noNaN.tsv --N=2504 --out=COORD_OUT_CONGEN_chr1 --ssf-format STANDARD`

But I ran into this error:

`Traceback (most recent call last):
  File "ldpred/LDpred.py", line 245, in <module>
    main()
  File "ldpred/LDpred.py", line 230, in main
    coord_genotypes.main(p_dict)
  File "/u/project/arboleda/joshuazh/GWAS_recode_VCF/ldpred/ldpred/coord_genotypes.py", line 728, in main
    debug=p_dict['debug'])
  File "/u/project/arboleda/joshuazh/GWAS_recode_VCF/ldpred/ldpred/coord_genotypes.py", line 263, in coordinate_genot_ss
    ok_freq_snps = sp.negative(freq_discrepancy_snp)
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.`

From googling, it seems like this has happened before for other programs, and the solution has always been to update one of the following: numpy, scipy, h5py, and pandas. I've updated all of them, however, and it hasn't resolved the issue.

I know this might not be related to your code exactly, but I would appreciate any help you could offer. For now I'll just try to simply do as the error says and edit my local version of LDpred to use `~`.

Best,
Josh

EDIT: If it helps, simply changing sp.negative to `~` seems to work fine.

**Comment by bvilhjal** [comment]
Thanks, it seems that we should use logical_not instead. What version of numpy and python are you using?  I believe this could be a numpy v. 1.16.x issue.

**Comment by Ambrosinae** [comment]
I'm using numpy 1.16.1 and python 3.7.2.

**Comment by bvilhjal** [comment]
I fixed this now.
