### ISSUE TITLE
python3 ldpred CLI tool issue

### ISSUE THREAD

**Issue by vplagnol** [bvilhjal/ldpred#51]
I am using a python3 environment and I can run ldpred, the tests pass (thanks for the python3 compatibility) but the CLI seems broken.
I am not sure if I am doing something wrong or whether it's a python3 thing. Any thoughts?

```
ldpred
Traceback (most recent call last):
  File "/data/scratch/user/vincent/env-precisionhealth/bin/ldpred", line 11, in <module>
    load_entry_point('LDpred==1.0.0', 'console_scripts', 'ldpred')()
  File "/data/scratch/user/vincent/env-precisionhealth/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/scratch/user/vincent/env-precisionhealth/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/data/scratch/user/vincent/env-precisionhealth/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/data/scratch/user/vincent/env-precisionhealth/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'LDpred'
```

**Comment by bvilhjal** [comment]
Hi Vincent, 

Thanks for reporting this.  I'm not sure what causing this.  Could it be that you're trying to install it using pip, or some other package manager?  Would you mind sharing the command that produced the issue.  

I have no problems running LDpred.py using either python 2.7.x, or python 3.6.x

I hope this helps.

Best,
Bjarni

**Comment by vplagnol** [comment]
mmm... I am doing a
```
python setup.py  install
```

which I suppose is the way to go? This is really strange because I see the LDpred egg file. I really am puzzled by the python package management system, and I must be doing something wrong.

**Comment by bvilhjal** [comment]
Ok, that explains it.  I recently updated the version, and I haven't packaged it properly yet.  Hence, please don't use setup.py.

Until that is fixed, please just clone the repository and then you should be able to just run LDpred by writing
`python LDpred.py -h`

I hope this helps.  Alternatively, I plan tp fix the setup.py, and LDpred available on pip, later this week.

Cheers,
Bjarni

ps. fight on

**Comment by vplagnol** [comment]
Ah yes I may not have been clear. I can run ldpred in general, only the CLI interface (i.e. calling ldpred outside of the repo) crashes. As long as you are aware of the CLI limitation, all is well. Thanks.

And I had not noted that you were a USC grad... Fight on indeed.

**Comment by bvilhjal** [comment]
Should be fixed now.  Thanks for reporting.
