### ISSUE TITLE
PRS weights files were not found, 'score' on 'p+t' outputs

### ISSUE THREAD

**Issue by wym0072003** [bvilhjal/ldpred#52]
Hi,

I had got SNP weigh file from 'LDpred.py p+t' function. However, 'LDpred.py score' can't find these weight files result from 'p+t'.  
here is my code:
 python ../ldpred/LDpred.py p+t --cf coorout-raw --ldr 1647  --out PT-result-raw
 python ../ldpred/LDpred.py score --gf ../skat-input --rf PT-result-raw --pf pheno.txt --out PT-risk-score

says: 'PRS weights files were not found, This could be due to a misspecified --rf flag, or other issues.'
Thank you for help.

best,

Yiming

**Comment by bvilhjal** [comment]
Hi Yiming

You need to provide the file prefix in the --rf flag, and then specify --rf-format P+T

However, if you update your repository now, your current code should also work.

Cheers,
Bjarni
