### ISSUE TITLE
selection of risk score from 7 output files.

### ISSUE THREAD

**Issue by wym0072003** [bvilhjal/ldpred#53]
Hi Bjarni,

Sorry for bothering you again.

I have question in how to select the best risk sore from the seven output files (1,0.01,0.03.....0.003).
I count the number of non-zero effect sites and calculated the it's proportion among input sites (non-zero sites/all input sites). Let's say proportion is 0.06, then I selected the closest p (0.1) as my output. Is that right?

Or maybe I should specify the p for my data? If I specify the p (--f) in GIBBS process, the p should be the non-zero proportion in training data or testing data?
Thanks.

best,

Yiming

**Comment by bvilhjal** [comment]
Hi, 

I think you should try to validate with all of these values, i.e. calculate polygenic scores for all, and see how they do.

I hope that helps.

Best,
Bjarni
