### ISSUE TITLE
ImportError LDpred

### ISSUE THREAD

**Issue by g-menta** [bvilhjal/ldpred#54]
Hi,

I'm using Python 2.7.10. Taking inspiration from the "python3 ldpred CLI tool issue" thread, I used successfully the following CLI command 
`python /Users/giorgiamenta/Desktop/ldpred-master/LDpred.py -h`

However, when trying to run 
`python /Users/giorgiamenta/Desktop/ldpred-master/ldpred/coord_genotypes.py --help`

I get the following error:
`Traceback (most recent call last):
  File "/Users/giorgiamenta/Desktop/ldpred-master/ldpred/coord_genotypes.py", line 7, in <module>
    from ldpred import sum_stats_parsers
ImportError: cannot import name sum_stats_parsers`

Anybody knows what the problem might be? I'm pretty new to Python so I feel a bit lost.
Thanks!

**Comment by bvilhjal** [comment]
Hi, 

I modified the code alot in the last few weeks, and now you need to run 
`python LDpred.py coord -h`
to get the help for the first step.

I hope that helps.

Best,
Bjarni
