### ISSUE TITLE
[BUG] in use custom format

### ISSUE THREAD

**Issue by wavefancy** [bvilhjal/ldpred#56]
Hi Bjarni,

When using the CUSTOM format in the 1.0 version, we will got an error as:
```
TypeError: parse_sum_stats_custom() got an unexpected keyword argument 'chr'
```
This is because of an argument setting error in the Line 42 of ```sum_stats_parsers.py```.

change from chr to ch will fix this problem.

Best regards
Wallace

**Comment by bvilhjal** [comment]
Thanks for reporting.  I believe I fixed it now.
