### ISSUE TITLE
Without validation dataset,how can i conduct the step3 to calculate polygenic risk score?

### ISSUE THREAD

**Issue by Z199486H** [bvilhjal/ldpred#59]
Hey Bjarni,
       Appreciate for your LDpred,here is my question when i run my summary data.
       We only got reference genotype file,and conducted the first step successfully.But,when we run the step3 to calculate polygenic risk score,the warning messeage informed me:cannot find the phenotype from our file.
      We want to kown where is the problem located,or how to solve it and run step3 successfully.
Thanks a lot.

**Comment by bvilhjal** [comment]
Hi, 

You cannot run the 'score' step without validation/target genotypes.  However, if you don't care about the prediction accuracy, and only want the scores, then you can run it without a dummy phenotype, or the --only-score flag (which I just added).  

Regarding the phenotype format, you can use standard plink FAM phenotype file format. 

I hope this helps.

Best,
Bjarni

**Comment by Z199486H** [comment]
Hey Bjarni,
Under your patient help,i have got the score successfully.But there is doubt still perplexing me.The prediction is consistent with our GWAS results,but the correlation coefficient is negative.How could i explain it.Or where is the problem which result in the phenomenon.
Thanks.

**Comment by bvilhjal** [comment]
Hi, 

The negative correlation is possibly an old bug that I had fixed, but now seems to have come alive again.  For now, just ignore it.  I'll get to it in a future version.  Thanks for reporting this!

Best,
Bjarni

**Comment by Z199486H** [comment]
Dear Bjarni,
Thanks your reply,I appreciate that you have helped me so much on my current work.
Thank you!
