### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by raivivek** [bvilhjal/ldpred#6]
The program seems to crash at some point (after writing about 8.3Gb of data to the disk) with `Segmentation fault (core dumped)`. Since there is no helpful message, do you know what could be causing this error?

Thanks!

**Comment by raivivek** [comment]
I am running it on a machine with 256GB RAM; doesn't look like it should be the problem. I also ran it on a different node. But the error seems to come up in the same instance during the computation -- such that the output file is truncated to 8.3GB.

**Comment by raivivek** [comment]
@cx0 On a side note, how much memory does it really need?

**Comment by daniel-hui** [comment]
Hi, I realize this is much later than your original message but I've eyeballed some of the RAM usage so I thought I'd post. 

With ~7M SNPs and 1000 reference individuals the "ldpred" command used 240 GB RAM.
With ~7M SNPs and 3.7K reference individuals the "ldpred" command usage increased to 250 GB ram.
I am now running it per chromosome with ~7M SNPs and 1000 individuals, and in total it is using 270G RAM.

**Comment by bvilhjal** [comment]
I apologize for the high memory use.  The limiting factor is likely the LD step, where the memory usage scales quadratically in the size of the LD window.  Hence, if the memory usage is very large, please consider a smaller LD window.

**Comment by HongyanR** [comment]
hey, just a side point, I have been struggling with same thing today, and I wonder what you mean by "LD_FILE_PREFIX"? The ld file ends with extension ".LD"?

**Comment by bvilhjal** [comment]
I apologize for the slow reply on this, but I didn't notice your last comment as I closed the issue.  

Anyways, LD_FILE_PREFIX refers to the filename where the LD will be stored.

Also, I have made lots of changes to the code now, including bug fixes, so perhaps you can try the latest version.
