### ISSUE TITLE
Potential bug in reporting problematic SNPs

### ISSUE THREAD

**Issue by babak-ra** [bvilhjal/ldpred#61]
It appears that there is a problem in the number of SNPs ignored ([+](https://github.com/bvilhjal/ldpred/blob/44c66680b6c4e7a804e2c7ed39025ef3f92fce74/ldpred/coord_genotypes.py#L325)). I am not sure if `tot_num_non_matching_nts` should be increased when alleles are ambiguous.

**Comment by bvilhjal** [comment]
fixed now in v. 1.0.3

Thanks for reporting.
