### ISSUE TITLE
LDpred for missing effect sizes

### ISSUE THREAD

**Issue by vaxherra** [bvilhjal/ldpred#63]
Hi,

I am trying to test LDpred. I've noticed that LDpred cannot handle missing effect size estimates, i.e. NA, or other non-numerical values. 

The problem is that some GWAS summary statistics, for example from EBI Gwas Summary statistics, occasionally don't hold any float values for effect size estimates, be it OR or Beta. What happens there is LDpred crushes, and python reports: `ValueError: could not convert a string to float: 'NA'`. It took me some time to track this, as LDpred worked well on test data.

I guess LDpred could remove these variants and report them in the log file.

**Comment by bvilhjal** [comment]
Thanks for reporting this.  I believe I've fixed this issue on master.

Cheers,
Bjarni

**Comment by gabraham** [comment]
@bvilhjal I've run into similar issues with other summary stats (GIANT 2014 Height) where SNPs with empty fields (e.g., rs786912 doesn't have an entry for Freq.Allele1.HapMapCEU). This leads to an off-by-one in parsing that line, and implausibly large beta values.
