### ISSUE TITLE
How can I get the beta in STANDARD format?

### ISSUE THREAD

**Issue by biostat0903** [bvilhjal/ldpred#71]
Hi Bjarni, 
I woule like to know how I can get the beta value in the STANDARD format, using the scaled genotype or no-scaled genotype? The two ways may get different beta value. I will be happy if you can tell me the right answer. Thanks for your kindly help.

Best, 
Sheng

**Comment by bvilhjal** [comment]
Hi Sheng, I apologize for the slow reply, but I was on holiday in April. 

Anyways, the actual beta value is not used, only the sign.  The betas used by LDpred internally are derived from the p-value.  Let me know if this doesn't answer your question.

Best,
Bjarni
