### ISSUE TITLE
using of three datasets: reference panel, summary statistics panel and validation dataset

### ISSUE THREAD

**Issue by wym0072003** [bvilhjal/ldpred#73]
Hi,

I am sorry for bothering you again. Just a little bit confused with the usage of three datasets: reference panel, summary statistics panel and validation dataset.

It looks the validation and reference panel can be the same dataset.
How about the summary statistic dataset, could it be the same the reference panel? That is to say, reference panel, summary stat dataset and validation dateset is the same data.
Thank you in advance.

best,

Yiming

**Comment by namjoub2** [comment]
also how to assign different columns when we have more than 1 summary data??

**Comment by bvilhjal** [comment]
Thanks for these comments, and I apologize the slow reply (was on holiday in April). 
If you have access to the inidividual-level data (on which the summary stats are generated), then I recommend using other methods, e.g. BOLT-LMM or penalised regressions.  LDpred is good for training on summary statistics when you do not have access to individual-level data.

Best.
