### ISSUE TITLE
prs adjustments

### ISSUE THREAD

**Issue by namjoub2** [bvilhjal/ldpred#79]
In the output score files, when I use the last column of score files  to generate auc (called as : cov-sex-pc-adj), I am getting much better AUC-performance than when I just use PRS only… that sounds like the last column represent the total variation not “the PRS adjusted for cov-sex-pc” . In that case the last term (adj) is not correct in output...it should be called "total variations"

IID	true_phens	PRS	  cov_adj	  pc_adj	  **cov_sex_pc_adj**

Please let us know about this …
thanks

**Comment by bvilhjal** [comment]
Thanks for your comment, and I apologize for the slow reply (I was on holidays in April).

You're right, these labels are wrong (or at least misleading).  These are not adjusted prediction, rather total predictions.  I updated the labels to reflect this.  

More generally, I currently recommend just importing the PRS into some other software, e.g. R, where you can study the relative importance of PCs, sex, and other covariates with and without the PRS.  

Best,
Bjarni
