### ISSUE TITLE
sum_stats_parsers flips effect size signs

### ISSUE THREAD

**Issue by babak-ra** [bvilhjal/ldpred#81]
I noticed that [when](https://github.com/bvilhjal/ldpred/blob/23896f12436f61d6b644b02be02d6306a03d74df/ldpred/sum_stats_parsers.py#L272) deriving betas from p-values and sign of effect sizes, their signs are flipped:

```beta = sp.sign(raw_beta) * stats.norm.ppf(pval_read / 2.0)```

since `stats.norm.ppf(pval_read / 2.0)` is always negative.

**Comment by N-damo** [comment]
same question

**Comment by jdijamco** [comment]
Fix committed to fork https://github.com/jdijamco/ldpred in https://github.com/jdijamco/ldpred/commit/1976b279cf30e7b4bb124bfbe6523edb6d67a959

**Comment by jdijamco** [comment]
Pull request sent: https://github.com/bvilhjal/ldpred/pull/88

**Comment by bvilhjal** [comment]
Should be fixed now..
