### ISSUE TITLE
SNP stds are not correctly computed

### ISSUE THREAD

**Issue by babak-ra** [bvilhjal/ldpred#83]
In [`coord_genotypes`](https://github.com/bvilhjal/ldpred/blob/23896f12436f61d6b644b02be02d6306a03d74df/ldpred/coord_genotypes.py#L383), Bernoulli distribution's theoretical variance formulation is used with the sample mean, i.e., `var = freqs * (1 - freqs)`; however, sample variance is going to be (slightly) different. This leads to incorrect LD calculations, e.g., the LD matrix could have diagonal elements that are larger than 1. I think sample variance should be used instead:

`snp_stds = sp.std(raw_snps, axis=1, dtype='float32')`

**Comment by jdijamco** [comment]
Babak found the fix for this, and I updated tests to cover it.  This is committed to fork https://github.com/jdijamco/ldpred in https://github.com/jdijamco/ldpred/commit/33f251fd245bd4cc67646c5dfa674556d859129e
Will work on sending a pull request to Bjarni.

**Comment by babak-ra** [comment]
I believe the same fix should be applied to the validation genotypes, [here](https://github.com/bvilhjal/ldpred/blob/23896f12436f61d6b644b02be02d6306a03d74df/ldpred/coord_genotypes.py#L402).

**Comment by jdijamco** [comment]
Fix to validation genotypes committed to https://github.com/jdijamco/ldpred/commit/97c5d1db2c4a5d780c27156fa57ed82594293d2b

**Comment by jdijamco** [comment]
Pull request sent: https://github.com/bvilhjal/ldpred/pull/88

**Comment by bvilhjal** [comment]
Should be fixed now.
