### ISSUE TITLE
LDpred Score error - missing phenotype file

### ISSUE THREAD

**Issue by Sabor117** [bvilhjal/ldpred#84]
I have been attempting to run LDpred score with just the output of the Gibbs sampler and an output prefix, as the the --help section of the script seemed to confirm that the only inputs you absolutely need.

However when running with just these options I was getting an error that: "Validation phenotypes were not found."

Similarly, when I then tried to add the (supposedly optional) command --gf with my reference genotype file I got another error of: "No phenotypes were found!"

I may be misunderstanding the usage of LDpred Score, but in the documentation it states that if there is no validation data it will "treat the LD reference genotypes as validation genotypes". Is this a mistake in the documentation and to run LDpred score you absolutely need a validation phenotype file?

**Comment by bvilhjal** [comment]
Hi, I apologise the slow reply.

I believe the option you're interested in is "--only-score". 

Cheers,
Bjarni
