### ISSUE TITLE
P+T

### ISSUE THREAD

**Issue by namjoub2** [bvilhjal/ldpred#85]
The program somehow unable to read the P+T file 
LDpred1.py p+t --cf ref-psc1 --ldr 1000 --out pt  --p 0.0001
1) a pt file being generated =  pt_P+T_r0.20_p1.0000e-04.txt
2) change the file name above  to just pt with the same  prefix  
LDpred1.py score --gf psc4 --rf pt --out pscprepPT --pf psc4.fam --pf-format FAM --rf-format P+T --pcs-file PCpsc.txt
parsing phenotypes
psc4.fam
Parsed 1763 phenotypes successfully
Traceback (most recent call last):
  File "/usr/local/ldpred/1.0.0/LDpred1.py", line 300, in <module>
    main()
  File "/usr/local/ldpred/1.0.0/LDpred1.py", line 293, in main
    validate.main(p_dict)
  File "/usr/local/ldpred/1.0.0/ldpred1/validate.py", line 721, in main
    assert not prs_file_is_missing, 'No SNP weights file was found.  A prefix to these should be provided via the --rf flag. Note that the prefix should exclude the _LDpred_.. extension or file ending. '
AssertionError: No SNP weights file was found.  A prefix to these should be provided via the --rf flag. Note that the prefix should exclude the _LDpred_.. extension or file ending.

I am not using LDpred here but p+t option.
appreciate your helps...

**Comment by mathieu-lemire** [comment]
Same problem. 

bvilhjal, I feel a lot of issues would find a resolution if you would write proper documentation, that you could test yourself.  This is lacking.

**Comment by melkesyre** [comment]
I have the exact same issue. Everything else works, but I am getting the "no SNP weights found" error when trying to generate a P+T score.

**Comment by bvilhjal** [comment]
Thanks for this error report.  I believe I've fixed it now.

**Comment by marine11** [comment]
Hello
I have the same problem. I use v.1.0.10.
Has it been resolved?
Thank you.
