### ISSUE TITLE
LDpred.py script referred to in documentation not supplied in pip install with Python 3.6 

### ISSUE THREAD

**Issue by delocalizer** [bvilhjal/ldpred#86]
Reproduce:
```
[user@host]$ python --version
Python 3.6.1
```

Following install instructions from the REAME.md:
```
pip install ldpred
```
(exits successfully)

The documentation then refers to a command-line script `LDpred.py`, which does not appear to have been provided anywhere from the pip installation.

There does appear a script `ldpred` placed into the `bin/` directory but it is broken (running it gives ```ModuleNotFoundError: No module named 'LDpred'```)

**Comment by bvilhjal** [comment]
Thanks for the comment.  

The folder structure that you are describing sounds weird.  Perhaps you can try reinstalling it locally using the --user flag when running pip.  Also, the script that you should be running is LDpred (not ldpred).  

I hope that helps.

**Comment by delocalizer** [comment]
Actually, it doesn't help. I'm not trying to run the `ldpred` script. I'd like to run the `LDpred.py` script as described in the documentation, the issue is that running `pip install ldpred` (with or without the `--user` flag) does not install anything called `LDpred.py` anywhere on the system, which I verified by running `find` on the entire filesystem from `/` down. I merely noted that a (broken) script called `ldpred` is installed to `/usr/local/bin` after running `pip install ldpred`.

I suggest that the pip distribution for 1.0.6 is broken, or at least inconsistent with what the documentation describes.
