### ISSUE TITLE
Genotypes

### ISSUE THREAD

**Issue by swvanderlaan** [bvilhjal/ldpred#9]
Hi,

Not so much an issue, rather some questions regarding genotypes of the validation data.

From your explanation in the Readme I deduce that one can only use hard-coded genotypes? So I have to 

1.  decide whether I want to filter the imputed data (I used `IMPUTE2`) that I intend to use?
2.  convert to hard-coded genotypes using `PLINK v1.9beta` for instance?

And thus, one cannot use imputed probabilities or dosages when calculating polygenic scores?

Thanks!

Sander

**Comment by bvilhjal** [comment]
Yes, you are correct.  You likely have to convert to 0/1/2 genotypes.
