### ISSUE TITLE
LDpred rho values

### ISSUE THREAD

**Issue by Minta821** [bvilhjal/ldpred#90]
Hi Bjarni J. Vilhja´lmsson,
While I was working on the ldpred with different rho values ( the sample size is 125000), ldpred works well on many rho values, but when it reaches rho 0.03 (even it is converged), it shows a sudden drop in AUC... Again it improves the AUC and offers  the best AUC at rho 0.01.
But with the ldpred-inf model, it offer almost the same performance of rho 0.01.
Why do  this pattern happens in the AUC with different rho values? Is it due to any convergence problem which can be changed by adjusting any parameters in MCMC procedures?
 Do the ldpred-inf model using any MCMC process?
Regards,
Thomas

**Comment by wavefancy** [comment]
It seems that the large N problem still needs to be fixed, having the same problem with a large sample size.

**Comment by bvilhjal** [comment]
I believe I've improved this now.  Please try it again..
