### ISSUE TITLE
Killed: 9

### ISSUE THREAD

**Issue by wagrob** [bvilhjal/ldpred#91]
Hi Bjarni,

I have a problem using LDpred in the second step of the data pipeline. 

`python LDpred.py gibbs --cf=coordinated --ldr=3000 --ldf=ldfile --N=900000 --out=resultfile` quits with a simple error message without producing results.

I invoke the LDpred code from a batch file and get the following error:

Calculating LD information w. radius 3000
./step2: line 2: 43328 Killed: 9

I already tried to scale down the radius to 300 or use the --hickle-ld flag, but it doesn't help.

Can you?

**Comment by bvilhjal** [comment]
Hmm, this looks like a HPC or cluster issue that is not directly related to ldpred, and perhaps something like you using more memory than you reserved.
