### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by jystatistics** [bvilhjal/ldpred#93]
Hi,

I try to install ldpred in my notebook. But I have error message as shown below. I upgraded my pip, but it does not help to install in my computer. 

I appreciate any comment for this problem. Thank you.

![1](https://user-images.githubusercontent.com/39386861/59643854-4807df80-911f-11e9-82bd-2b74b5a80a77.PNG)

**Comment by KClaudio21** [comment]
Hi jystatistics! Were you able to solve this issue? I have the same issue

**Comment by bvilhjal** [comment]
Thanks for this bug report.  This is probably a problem with installing [plinkio](https://pypi.org/project/plinkio/).  I hope to switch to pandas for handling plink files in the future, which should resolve this.

**Comment by bvilhjal** [comment]
I believe I've at least fixed the pip install ldpred issue now.  Thanks for reporting the error.

**Comment by KClaudio21** [comment]
Perfect! Thank you so much!

?

Best,

Karla


Karla Claudio, Ph.D.

Postdoctoral Fellow in Genomic Medicine

Department of Pharmacotherapy and Translational Research

College of Pharmacy

University of Florida

Email: KClaudio@cop.ufl.edu

________________________________
