### ISSUE TITLE
Import error from cplinkio - GLIBC2.14

### ISSUE THREAD

**Issue by sn-GT** [bvilhjal/ldpred#96]
Hi 
I have successfully installed ldpred, plinkio, numpy and scipy on the server and am able to import these packages on python. However, when I run the command "python LDpred.py coord -h" , I get import error from cplinkio - glibc2.14 (see error below).  How do I proceed with it ? 

python LDpred.py coord -h
Traceback (most recent call last):
  File "LDpred.py", line 4, in <module>
    from ldpred import coord_genotypes
  File "/gpfs/pace1/project/bio-gibson/snagpal3/Tools/LDPRED/ldpred/ldpred/coord_genotypes.py", line 11, in <module>
    from ldpred import plinkfiles
  File "/gpfs/pace1/project/bio-gibson/snagpal3/Tools/LDPRED/ldpred/ldpred/plinkfiles.py", line 7, in <module>
    from plinkio import plinkfile
  File "/nv/hp10/snagpal3/.conda/envs/ldpred/lib/python3.6/site-packages/plinkio/plinkfile.py", line 1, in <module>
    from . import cplinkio
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /nv/hp10/snagpal3/.conda/envs/ldpred/lib/python3.6/site-packages/plinkio/cplinkio.cpython-36m-x86_64-linux-gnu.so)

On running the command below, it shows that I have GLIBC on my system:
strings /lib64/libc.so.6|grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_PRIVATE

**Comment by choishingwan** [comment]
You don't have glibc 2.14 though.

**Comment by bvilhjal** [comment]
Thanks for this bug report.  I'm not sure how I can help you.  I believe this is really a problem with installing [plinkio](https://pypi.org/project/plinkio/).
