### ISSUE TITLE
Are these all of columns in summary statistics require to run LDpred.py coord?

### ISSUE THREAD

**Issue by jystatistics** [bvilhjal/ldpred#98]
Hi,

I'm trying to run the test data with LDpred.py. 

Here is my error message that I have now. 

Traceback (most recent call last):
  File "LDpred.py", line 300, in <module>
    main()
  File "LDpred.py", line 285, in main
    coord_genotypes.main(p_dict)
  File "/data1/home/jungj7/00_Pipeline/08_GRS/LDpred/ldpred/ldpred/coord_genotypes.py", line 566, in main
    sum_stats_parsers.parse_sum_stats(h5f, p_dict, bimfile, summary_dict)
  File "/data1/home/jungj7/00_Pipeline/08_GRS/LDpred/ldpred/ldpred/sum_stats_parsers.py", line 73, in parse_sum_stats
    control_n=p_dict['control_n'], **ss_args)
  File "/data1/home/jungj7/00_Pipeline/08_GRS/LDpred/ldpred/ldpred/sum_stats_parsers.py", line 161, in parse_sum_stats_custom
    assert eff in header_dict, 'Effect size column not found in summary statistic file'
AssertionError: Effect size column not found in summary statistic file

**And I looked at the file of sum_stats_parsers.py and noticed that there is** 

![1](https://user-images.githubusercontent.com/39386861/60850298-87b46b00-a1a3-11e9-8998-33268a7cd484.PNG)
![2](https://user-images.githubusercontent.com/39386861/60850299-87b46b00-a1a3-11e9-99db-47ce5a915d3b.PNG)

Can anyone help on this issue? Do I have to have each column of summary statistics to run LDpred.py?

Thank you.

**Comment by jPontix** [comment]
You have to change the header in this way:

> chr     pos     ref     alt     reffrq  info    rs       pval    effalt

When you will run the command remember to write --ssf-format STANDARD

**Comment by jPontix** [comment]
You have to change the header in this way:

> chr pos ref alt reffrq info rs pval effalt

All these columns are required.
When you will run the command remember to write --ssf-format STANDARD.

**Comment by choishingwan** [comment]
Alternatively, you can use 

```
--ssf-format CUSTOM  --chr CHR   --pos pos  --A1 A1  --A2 A2 --rs rs  --pval pval  --eff EFF
```
to provide a more flexible input option (might also need to specify `--beta` if your summary statistics is in the form of beta instead of OR

**Comment by bvilhjal** [comment]
@choishingwan @jPontix Thanks for the help on this reply!
